import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import Header from "@/components/Header/Header";
import { Roboto } from "next/font/google";
import Footer2 from "@/components/Footer/Footer";

const robotoSemi = Roboto({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/baseLogo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={robotoSemi.className}>
        <Provider>
          <Header />
          {children}
          <Footer2 />
        </Provider>
      </body>
    </html>
  );
}
